apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-vm-disk-1
  namespace: vm-test-ns
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ocs-storagecluster-ceph-rbd-virtualization
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-vm-disk-2
  namespace: vm-test-ns
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ocs-storagecluster-ceph-rbd-virtualization
  resources:
    requests:
      storage: 5Gi
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: test-vm
  namespace: vm-test-ns
spec:
  running: false
  template:
    spec:
      domain:
        devices:
          disks:
          - name: disk1
            disk:
              bus: virtio
          - name: disk2
            disk:
              bus: virtio
        resources:
          requests:
            memory: 1Gi
      volumes:
      - name: disk1
        persistentVolumeClaim:
          claimName: test-vm-disk-1
      - name: disk2
        persistentVolumeClaim:
          claimName: test-vm-disk-2
