---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restores-pvc
  namespace: vmfr-pod-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: <your-storage-class>  # Uncomment and specify if needed
